
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Anton.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CountryLocations
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CountryLocations()
    {

        this.Hospitals = new HashSet<Hospitals>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Country_Name { get; set; }



    public virtual Countries Countries { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Hospitals> Hospitals { get; set; }

}

}
