//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CoTecDBEntities : DbContext
{
    public CoTecDBEntities()
        : base("name=CoTecDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Contacted_Person> Contacted_Person { get; set; }
    public virtual DbSet<Continent> Continents { get; set; }
    public virtual DbSet<Country> Countries { get; set; }
    public virtual DbSet<CountryLocation> CountryLocations { get; set; }
    public virtual DbSet<EnforcedMeasurement> EnforcedMeasurements { get; set; }
    public virtual DbSet<Event> Events { get; set; }
    public virtual DbSet<Hospital_ICUs> Hospital_ICUs { get; set; }
    public virtual DbSet<Hospital_Medications> Hospital_Medications { get; set; }
    public virtual DbSet<Hospital_Patients> Hospital_Patients { get; set; }
    public virtual DbSet<Hospital> Hospitals { get; set; }
    public virtual DbSet<Medication> Medications { get; set; }
    public virtual DbSet<Pathology> Pathologies { get; set; }
    public virtual DbSet<Patient_Medications> Patient_Medications { get; set; }
    public virtual DbSet<Patient_Pathologies> Patient_Pathologies { get; set; }
    public virtual DbSet<Patient_Status> Patient_Status { get; set; }
    public virtual DbSet<Patient> Patients { get; set; }
    public virtual DbSet<SanityMeasurement> SanityMeasurements { get; set; }
}
