//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anton.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoTecDBEntities : DbContext
    {
        public CoTecDBEntities()
            : base("name=CoTecDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contacted_Person> Contacted_Person { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CountryLocation> CountryLocations { get; set; }
        public virtual DbSet<EnforcedMeasurement> EnforcedMeasurements { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Hospital_ICUs> Hospital_ICUs { get; set; }
        public virtual DbSet<Hospital_Medications> Hospital_Medications { get; set; }
        public virtual DbSet<Hospital_Patients> Hospital_Patients { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<Pathology> Pathologies { get; set; }
        public virtual DbSet<Patient_Medications> Patient_Medications { get; set; }
        public virtual DbSet<Patient_Pathologies> Patient_Pathologies { get; set; }
        public virtual DbSet<Patient_Status> Patient_Status { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<SanityMeasurement> SanityMeasurements { get; set; }
    }
}
