//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anton.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoTecDBEntities : DbContext
    {
        public CoTecDBEntities()
            : base("name=CoTecDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contacted_Person> Contacted_Person { get; set; }
        public virtual DbSet<Continents> Continents { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<CountryLocations> CountryLocations { get; set; }
        public virtual DbSet<EnforcedMeasurements> EnforcedMeasurements { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Hospital_ICUs> Hospital_ICUs { get; set; }
        public virtual DbSet<Hospitals> Hospitals { get; set; }
        public virtual DbSet<Medications> Medications { get; set; }
        public virtual DbSet<Pathologies> Pathologies { get; set; }
        public virtual DbSet<Patient_Status> Patient_Status { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<SanityMeasurements> SanityMeasurements { get; set; }
    }
}
