//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Contacted_Person
{
    public int Id { get; set; }
    public Nullable<int> SSN { get; set; }
    public Nullable<int> Patient_SSN { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public string Address { get; set; }
    public string Email { get; set; }
    public Nullable<int> Age { get; set; }

    public virtual Patient Patient { get; set; }
}

public partial class Continent
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Continent()
    {
        this.Countries = new HashSet<Country>();
    }

    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Country> Countries { get; set; }
}

public partial class Country
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Country()
    {
        this.CountryLocations = new HashSet<CountryLocation>();
        this.EnforcedMeasurements = new HashSet<EnforcedMeasurement>();
        this.Hospitals = new HashSet<Hospital>();
        this.Patients = new HashSet<Patient>();
        this.Patients1 = new HashSet<Patient>();
    }

    public string Name { get; set; }
    public string Continent_Name { get; set; }

    public virtual Continent Continent { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CountryLocation> CountryLocations { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EnforcedMeasurement> EnforcedMeasurements { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Hospital> Hospitals { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Patient> Patients { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Patient> Patients1 { get; set; }
}

public partial class CountryLocation
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Country_Name { get; set; }

    public virtual Country Country { get; set; }
}

public partial class EnforcedMeasurement
{
    public int Id { get; set; }
    public string Country_Name { get; set; }
    public Nullable<int> Measurement_Id { get; set; }
    public Nullable<System.DateTime> Start_Date { get; set; }
    public Nullable<System.DateTime> End_Date { get; set; }

    public virtual Country Country { get; set; }
    public virtual SanityMeasurement SanityMeasurement { get; set; }
}

public partial class Event
{
    public int Id { get; set; }
    public string Status_Event { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> Patient_SSN { get; set; }

    public virtual Patient Patient { get; set; }
    public virtual Patient_Status Patient_Status { get; set; }
}

public partial class Hospital
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Hospital()
    {
        this.Hospital_ICUs = new HashSet<Hospital_ICUs>();
        this.Hospital_Medications = new HashSet<Hospital_Medications>();
        this.Hospital_Patients = new HashSet<Hospital_Patients>();
        this.Patients = new HashSet<Patient>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public Nullable<int> ICU_Capacity { get; set; }
    public Nullable<int> Capacity { get; set; }
    public string Manager_Name { get; set; }
    public string Phone { get; set; }
    public string Country_Name { get; set; }

    public virtual Country Country { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Hospital_ICUs> Hospital_ICUs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Hospital_Medications> Hospital_Medications { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Hospital_Patients> Hospital_Patients { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Patient> Patients { get; set; }
}

public partial class Hospital_ICUs
{
    public int Id { get; set; }
    public string ICU_Patient { get; set; }
    public Nullable<int> Hospital_Id { get; set; }

    public virtual Hospital Hospital { get; set; }
}

public partial class Hospital_Medications
{
    public int Id { get; set; }
    public Nullable<int> Hospital_Id { get; set; }
    public Nullable<int> Medication_Id { get; set; }

    public virtual Hospital Hospital { get; set; }
    public virtual Medication Medication { get; set; }
}

public partial class Hospital_Patients
{
    public int Id { get; set; }
    public string Patient { get; set; }
    public Nullable<int> Hospital_Id { get; set; }

    public virtual Hospital Hospital { get; set; }
}

public partial class Medication
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Medication()
    {
        this.Hospital_Medications = new HashSet<Hospital_Medications>();
        this.Patient_Medications = new HashSet<Patient_Medications>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Provider { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Hospital_Medications> Hospital_Medications { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Patient_Medications> Patient_Medications { get; set; }
}

public partial class Pathology
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pathology()
    {
        this.Patient_Pathologies = new HashSet<Patient_Pathologies>();
    }

    public string Name { get; set; }
    public string Symptoms { get; set; }
    public string Description { get; set; }
    public string Treatment { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Patient_Pathologies> Patient_Pathologies { get; set; }
}

public partial class Patient
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Patient()
    {
        this.Contacted_Person = new HashSet<Contacted_Person>();
        this.Events = new HashSet<Event>();
        this.Patient_Medications = new HashSet<Patient_Medications>();
        this.Patient_Pathologies = new HashSet<Patient_Pathologies>();
    }

    public int SSN { get; set; }
    public string First_Name { get; set; }
    public string Last_Name { get; set; }
    public Nullable<bool> Hospitalized { get; set; }
    public Nullable<bool> ICU { get; set; }
    public Nullable<int> Age { get; set; }
    public string Residence { get; set; }
    public string Country_Birth { get; set; }
    public Nullable<int> Hospital_Id { get; set; }
    public string Status { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contacted_Person> Contacted_Person { get; set; }
    public virtual Country Country { get; set; }
    public virtual Country Country1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Event> Events { get; set; }
    public virtual Hospital Hospital { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Patient_Medications> Patient_Medications { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Patient_Pathologies> Patient_Pathologies { get; set; }
    public virtual Patient_Status Patient_Status { get; set; }
}

public partial class Patient_Medications
{
    public int Id { get; set; }
    public Nullable<int> Patient_SSN { get; set; }
    public Nullable<int> Medication_Id { get; set; }

    public virtual Medication Medication { get; set; }
    public virtual Patient Patient { get; set; }
}

public partial class Patient_Pathologies
{
    public int Id { get; set; }
    public Nullable<int> Patient_SSN { get; set; }
    public string Pathology_Name { get; set; }

    public virtual Pathology Pathology { get; set; }
    public virtual Patient Patient { get; set; }
}

public partial class Patient_Status
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Patient_Status()
    {
        this.Events = new HashSet<Event>();
        this.Patients = new HashSet<Patient>();
    }

    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Event> Events { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Patient> Patients { get; set; }
}

public partial class SanityMeasurement
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SanityMeasurement()
    {
        this.EnforcedMeasurements = new HashSet<EnforcedMeasurement>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EnforcedMeasurement> EnforcedMeasurements { get; set; }
}
