
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Anton.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EnforcedMeasurements
{

    public int Id { get; set; }

    public string Country_Name { get; set; }

    public Nullable<int> Measurement_Id { get; set; }

    public Nullable<System.DateTime> Start_Date { get; set; }

    public Nullable<System.DateTime> End_Date { get; set; }

    public Nullable<bool> State { get; set; }



    public virtual Countries Countries { get; set; }

    public virtual SanityMeasurements SanityMeasurements { get; set; }

}

}
