//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnforcedMeasurements
    {
        public int Id { get; set; }
        public string Country_Name { get; set; }
        public Nullable<int> Measurement_Id { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual SanityMeasurements SanityMeasurements { get; set; }
    }
}
