//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital_Medications
    {
        public int Id { get; set; }
        public Nullable<int> Hospital_Id { get; set; }
        public Nullable<int> Medication_Id { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Medication Medication { get; set; }
    }
}
