
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Anton.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Patients
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Patients()
    {

        this.Contacted_Person = new HashSet<Contacted_Person>();

        this.Events = new HashSet<Events>();

        this.Patient_Medications = new HashSet<Patient_Medications>();

        this.Patient_Pathologies = new HashSet<Patient_Pathologies>();

    }


    public int SSN { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public Nullable<bool> Hospitalized { get; set; }

    public Nullable<bool> ICU { get; set; }

    public Nullable<int> Age { get; set; }

    public string Residence { get; set; }

    public string Country_Birth { get; set; }

    public Nullable<int> Hospital_Id { get; set; }

    public string Status { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contacted_Person> Contacted_Person { get; set; }

    public virtual Countries Countries { get; set; }

    public virtual Countries Countries1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Events> Events { get; set; }

    public virtual Hospitals Hospitals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Patient_Medications> Patient_Medications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Patient_Pathologies> Patient_Pathologies { get; set; }

    public virtual Patient_Status Patient_Status { get; set; }

}

}
