
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Anton.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Patient_Pathologies
{

    public int Id { get; set; }

    public Nullable<int> Patient_SSN { get; set; }

    public string Pathology_Name { get; set; }



    public virtual Pathologies Pathologies { get; set; }

    public virtual Patients Patients { get; set; }

}

}
