//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Pathologies
    {
        public int Id { get; set; }
        public Nullable<int> Patient_SSN { get; set; }
        public string Pathology_Name { get; set; }
    
        public virtual Pathologies Pathologies { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
