//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anton.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Contacted_Person = new HashSet<Contacted_Person>();
            this.Patient_Status = new HashSet<Patient_Status>();
            this.Medications = new HashSet<Medications>();
            this.Pathologies = new HashSet<Pathologies>();
        }
    
        public string SSN { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Hospitalized { get; set; }
        public string ICU { get; set; }
        public Nullable<int> Age { get; set; }
        public string Residence { get; set; }
        public string Country_Birth { get; set; }
        public Nullable<int> Hospital_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacted_Person> Contacted_Person { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Countries Countries1 { get; set; }
        public virtual Hospitals Hospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Status> Patient_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medications> Medications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pathologies> Pathologies { get; set; }
    }
}
