//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anton
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Contacted_Person = new HashSet<Contacted_Person>();
            this.Events = new HashSet<Event>();
            this.Patient_Medications = new HashSet<Patient_Medications>();
            this.Patient_Pathologies = new HashSet<Patient_Pathologies>();
        }
    
        public int SSN { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<bool> Hospitalized { get; set; }
        public Nullable<bool> ICU { get; set; }
        public Nullable<int> Age { get; set; }
        public string Residence { get; set; }
        public string Country_Birth { get; set; }
        public Nullable<int> Hospital_Id { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacted_Person> Contacted_Person { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Hospital Hospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Medications> Patient_Medications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Pathologies> Patient_Pathologies { get; set; }
        public virtual Patient_Status Patient_Status { get; set; }
    }
}
